### ISSUE TITLE
ADB Root Requirement (su alternative?)

### ISSUE THREAD

**Issue by Kevin4562** [mauricelam/btsnoop-rs#2]
For btsnoop-extcap,

My device is currently rooted but running a production build and cannot run "adb root". Would an implementation be possible that uses su prefixed commands instead?

Thanks!

**Comment by mauricelam** [comment]
Sure, it makes sense to add that.

I don't have a device in that configuration to test against, can you confirm whether the below commands work?

```
adb shell su cat /data/misc/bluetooth/logs/btsnoop_hci.log > /tmp/btsnoop.log
wireshark /tmp/btsnoop.log
```

**Comment by Kevin4562** [comment]
The following works on my system:
```
adb shell su -c 'cat /data/misc/bluetooth/logs/btsnoop_hci.log' > btsnoop.log
Wireshark.exe btsnoop.log
```

Currently, I have just swapped the cmd args within shell to the following and it is working (after modifying the root checks):
`cmd.args(["-s", serial, "shell", "su", "-c", &("'" + command + "'")]);`

**Comment by Kevin4562** [comment]
I also had to add character returns to the mode matching, not sure if that is related:

```
match output.stdout.as_slice() {
    b"full\n" => Ok(BtsnoopLogMode::Full),
    b"full\r\n" => Ok(BtsnoopLogMode::Full),
    b"filtered\n" => Ok(BtsnoopLogMode::Filtered),
    b"filtered\r\n" => Ok(BtsnoopLogMode::Filtered),
    b"disabled\n" => Ok(BtsnoopLogMode::Disabled),
    b"disabled\r\n" => Ok(BtsnoopLogMode::Disabled),
    _ => Err(anyhow!("Unknown BTsnoop log mode")),
}
```

**Comment by mauricelam** [comment]
Thanks for looking into the issues. I think I have fixed the issues you described in the `rooted` branch https://github.com/mauricelam/btsnoop-rs/tree/rooted, and I am now setting up on Windows to verify.
